# frozen_string_literal: true

source "https://rubygems.org"

gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'bcrypt'
gem 'rack-cors'

gem 'stackprof'

group :development do
  gem 'irb'
end
